In [4]:
import numpy as np
array = np.array([1,2,3,4,5])

In [6]:
mean= np.mean(array)

In [7]:
print(mean)

3.0


In [8]:
median= np.median(data)

In [10]:
print(median)

3.0


In [11]:
max= np.max(data)

In [12]:
print(max)

5


In [13]:
stv_dev= np.std(array)

In [14]:
print(stv_dev)

1.4142135623730951


In [15]:
total= np.sum(array)

In [16]:
print(total)

15


In [18]:
reshaped_array= array.reshape((5,1))

In [20]:
print(reshaped_array)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [24]:
array1= np.array([1,2,3])
array2= np.array([4,5,6])
concatenated=np.concatenate((array1,array2))

In [25]:
print(concatenated)

[1 2 3 4 5 6]


In [37]:
numbers=np.linspace(0,10,5)

In [38]:
print(numbers)

[ 0.   2.5  5.   7.5 10. ]


In [44]:
range_array=np.arange(0,10,2)

In [45]:
print(range_array)

[0 2 4 6 8]
